version: '3.4'

services:
  seq:
    image: datalust/seq:latest

  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "5100:80"
